// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3hLq7_RwJpL_3K-KxZeT4ZLZ4QHytD8',
    appId: '1:239898125237:android:a95caa6e4bbbfd4b606ffc',
    messagingSenderId: '239898125237',
    projectId: 'itrade-965d8',
    storageBucket: 'itrade-965d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgh7W0ZUuLKJkgjMp8W8KyTpzoZvAB2J8',
    appId: '1:239898125237:ios:bbc42e0a24e0d38d606ffc',
    messagingSenderId: '239898125237',
    projectId: 'itrade-965d8',
    storageBucket: 'itrade-965d8.firebasestorage.app',
    androidClientId: '239898125237-39qdn6qqppi475d0c40a7hfmpkcmoaei.apps.googleusercontent.com',
    iosClientId: '239898125237-7qiah2g6rbanoggphpfrfe77i3t467ev.apps.googleusercontent.com',
    iosBundleId: 'com.ihsueh.itrade',
  );
}
