/// Strategy model representing trading strategies
class Strategy {
  final int id;
  final String name;
  final String? description;
  final String type;
  final String status;
  final String? exchange;
  final String? symbol;
  final String? normalizedSymbol; // Auto-generated by backend
  final String marketType; // Auto-generated: 'spot', 'perpetual', 'futures'
  final Map<String, dynamic>? parameters;
  final Map<String, dynamic>? initialDataConfig;
  final Map<String, dynamic>? subscription;
  final String? errorMessage;
  final DateTime? lastExecutionTime;
  final DateTime createdAt;
  final DateTime updatedAt;
  final StrategyPerformance? performance;

  Strategy({
    required this.id,
    required this.name,
    this.description,
    required this.type,
    required this.status,
    this.exchange,
    this.symbol,
    this.normalizedSymbol,
    this.marketType = 'spot',
    this.parameters,
    this.initialDataConfig,
    this.subscription,
    this.errorMessage,
    this.lastExecutionTime,
    required this.createdAt,
    required this.updatedAt,
    this.performance,
  });

  factory Strategy.fromJson(Map<String, dynamic> json) {
    return Strategy(
      id: _parseInt(json['id']),
      name: json['name'] as String,
      description: json['description'] as String?,
      type: json['type'] as String,
      status: json['status'] as String,
      exchange: json['exchange'] as String?,
      symbol: json['symbol'] as String?,
      normalizedSymbol: json['normalizedSymbol'] as String?,
      marketType: json['marketType'] as String? ?? 'spot',
      parameters: json['parameters'] as Map<String, dynamic>?,
      initialDataConfig: json['initialDataConfig'] as Map<String, dynamic>?,
      subscription: json['subscription'] as Map<String, dynamic>?,
      errorMessage: json['errorMessage'] as String?,
      lastExecutionTime: json['lastExecutionTime'] != null
          ? DateTime.parse(json['lastExecutionTime'] as String)
          : null,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      performance: json['performance'] != null
          ? StrategyPerformance.fromJson(json['performance'] as Map<String, dynamic>)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'type': type,
      'status': status,
      'exchange': exchange,
      'symbol': symbol,
      'parameters': parameters,
      'initialDataConfig': initialDataConfig,
      'subscription': subscription,
      'errorMessage': errorMessage,
      'lastExecutionTime': lastExecutionTime?.toIso8601String(),
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  bool get isActive => status == 'active';
  bool get isStopped => status == 'stopped';
  bool get isPaused => status == 'paused';
  bool get isError => status == 'error';
}

class StrategyPerformance {
  final double totalPnL;
  final double roi;
  final double winRate;
  final double maxDrawdown;
  final int totalOrders;
  final int winningTrades;
  final int losingTrades;
  final int longOrdersFilledCount;
  final int shortOrdersFilledCount;

  StrategyPerformance({
    required this.totalPnL,
    required this.roi,
    required this.winRate,
    required this.maxDrawdown,
    required this.totalOrders,
    required this.winningTrades,
    required this.losingTrades,
    required this.longOrdersFilledCount,
    required this.shortOrdersFilledCount,
  });

  factory StrategyPerformance.fromJson(Map<String, dynamic> json) {
    return StrategyPerformance(
      totalPnL: _parseDouble(json['totalPnL']),
      roi: _parseDouble(json['roi']),
      winRate: _parseDouble(json['winRate']),
      maxDrawdown: _parseDouble(json['maxDrawdown']),
      totalOrders: _parseInt(json['totalOrders']),
      winningTrades: _parseInt(json['winningTrades']),
      losingTrades: _parseInt(json['losingTrades']),
      longOrdersFilledCount: _parseInt(json['longOrdersFilledCount']),
      shortOrdersFilledCount: _parseInt(json['shortOrdersFilledCount']),
    );
  }
}

/// Rebuilt performance data from the API (analytics endpoint)
class RebuiltPerformancePnL {
  final double realizedPnL;
  final double unrealizedPnL;
  final double totalPnL;
  final double totalFees;
  final double netPnL;
  final double roi;
  final double winRate;
  final double profitFactor;

  RebuiltPerformancePnL({
    required this.realizedPnL,
    required this.unrealizedPnL,
    required this.totalPnL,
    required this.totalFees,
    required this.netPnL,
    required this.roi,
    required this.winRate,
    required this.profitFactor,
  });

  factory RebuiltPerformancePnL.fromJson(Map<String, dynamic> json) {
    return RebuiltPerformancePnL(
      realizedPnL: _parseDouble(json['realizedPnL']),
      unrealizedPnL: _parseDouble(json['unrealizedPnL']),
      totalPnL: _parseDouble(json['totalPnL']),
      totalFees: _parseDouble(json['totalFees']),
      netPnL: _parseDouble(json['netPnL']),
      roi: _parseDouble(json['roi']),
      winRate: _parseDouble(json['winRate']),
      profitFactor: _parseDouble(json['profitFactor']),
    );
  }
}

class RebuiltPerformanceOrders {
  final int longFilledCount;
  final int longTotalCount;
  final int shortFilledCount;
  final int shortTotalCount;

  RebuiltPerformanceOrders({
    required this.longFilledCount,
    required this.longTotalCount,
    required this.shortFilledCount,
    required this.shortTotalCount,
  });

  int get totalFilled => longFilledCount + shortFilledCount;
  int get totalCount => longTotalCount + shortTotalCount;

  factory RebuiltPerformanceOrders.fromJson(Map<String, dynamic> json) {
    final long = json['long'] as Map<String, dynamic>? ?? {};
    final short = json['short'] as Map<String, dynamic>? ?? {};
    final longFilled = long['filled'] as Map<String, dynamic>? ?? {};
    final longTotal = long['total'] as Map<String, dynamic>? ?? {};
    final shortFilled = short['filled'] as Map<String, dynamic>? ?? {};
    final shortTotal = short['total'] as Map<String, dynamic>? ?? {};

    return RebuiltPerformanceOrders(
      longFilledCount: _parseInt(longFilled['count']),
      longTotalCount: _parseInt(longTotal['count']),
      shortFilledCount: _parseInt(shortFilled['count']),
      shortTotalCount: _parseInt(shortTotal['count']),
    );
  }
}

class RebuiltPerformanceActivity {
  final int winningTrades;
  final int losingTrades;

  RebuiltPerformanceActivity({
    required this.winningTrades,
    required this.losingTrades,
  });

  factory RebuiltPerformanceActivity.fromJson(Map<String, dynamic> json) {
    return RebuiltPerformanceActivity(
      winningTrades: _parseInt(json['winningTrades']),
      losingTrades: _parseInt(json['losingTrades']),
    );
  }
}

class RebuiltPerformanceRisk {
  final double maxDrawdown;
  final double sharpeRatio;

  RebuiltPerformanceRisk({
    required this.maxDrawdown,
    required this.sharpeRatio,
  });

  factory RebuiltPerformanceRisk.fromJson(Map<String, dynamic> json) {
    return RebuiltPerformanceRisk(
      maxDrawdown: _parseDouble(json['maxDrawdown']),
      sharpeRatio: _parseDouble(json['sharpeRatio']),
    );
  }
}

class RebuiltPerformance {
  final RebuiltPerformancePnL pnl;
  final RebuiltPerformanceOrders? orders;
  final RebuiltPerformanceActivity? activity;
  final RebuiltPerformanceRisk? risk;

  RebuiltPerformance({
    required this.pnl,
    this.orders,
    this.activity,
    this.risk,
  });

  factory RebuiltPerformance.fromJson(Map<String, dynamic> json) {
    return RebuiltPerformance(
      pnl: RebuiltPerformancePnL.fromJson(
        json['pnl'] as Map<String, dynamic>? ?? {},
      ),
      orders: json['orders'] != null
          ? RebuiltPerformanceOrders.fromJson(
              json['orders'] as Map<String, dynamic>,
            )
          : null,
      activity: json['activity'] != null
          ? RebuiltPerformanceActivity.fromJson(
              json['activity'] as Map<String, dynamic>,
            )
          : null,
      risk: json['risk'] != null
          ? RebuiltPerformanceRisk.fromJson(
              json['risk'] as Map<String, dynamic>,
            )
          : null,
    );
  }
}

/// Position summary for a strategy (calculated from orders)
class StrategyPositionSummary {
  final double netExecutedPosition;
  final double pendingBuySize;
  final double pendingSellSize;
  final double totalBoughtSize;
  final double totalSoldSize;

  StrategyPositionSummary({
    required this.netExecutedPosition,
    required this.pendingBuySize,
    required this.pendingSellSize,
    required this.totalBoughtSize,
    required this.totalSoldSize,
  });

  factory StrategyPositionSummary.fromJson(Map<String, dynamic> json) {
    return StrategyPositionSummary(
      netExecutedPosition: _parseDouble(json['netExecutedPosition']),
      pendingBuySize: _parseDouble(json['pendingBuySize']),
      pendingSellSize: _parseDouble(json['pendingSellSize']),
      totalBoughtSize: _parseDouble(json['totalBoughtSize']),
      totalSoldSize: _parseDouble(json['totalSoldSize']),
    );
  }
}

/// Strategy PnL data
class StrategyPnL {
  final int strategyId;
  final String strategyName;
  final double totalPnl;
  final double realizedPnl;
  final double unrealizedPnl;
  final int totalOrders;
  final int filledOrders;

  StrategyPnL({
    required this.strategyId,
    required this.strategyName,
    required this.totalPnl,
    required this.realizedPnl,
    required this.unrealizedPnl,
    required this.totalOrders,
    required this.filledOrders,
  });

  factory StrategyPnL.fromJson(Map<String, dynamic> json) {
    return StrategyPnL(
      strategyId: _parseInt(json['strategyId']),
      strategyName: json['strategyName'] as String? ?? '',
      totalPnl: _parseDouble(json['pnl']),
      realizedPnl: _parseDouble(json['realizedPnl']),
      unrealizedPnl: _parseDouble(json['unrealizedPnl']),
      totalOrders: _parseInt(json['totalOrders']),
      filledOrders: _parseInt(json['filledOrders']),
    );
  }

  bool get isProfitable => totalPnl > 0;
  bool get isLoss => totalPnl < 0;
}

double _parseDouble(dynamic value, {double fallback = 0.0}) {
  if (value == null) {
    return fallback;
  }
  if (value is num) {
    return value.toDouble();
  }
  if (value is String) {
    return double.tryParse(value) ?? fallback;
  }
  return fallback;
}

int _parseInt(dynamic value, {int fallback = 0}) {
  if (value == null) {
    return fallback;
  }
  if (value is int) {
    return value;
  }
  if (value is num) {
    return value.toInt();
  }
  if (value is String) {
    final intValue = int.tryParse(value);
    if (intValue != null) {
      return intValue;
    }
    final doubleValue = double.tryParse(value);
    if (doubleValue != null) {
      return doubleValue.toInt();
    }
  }
  return fallback;
}
